export {default as Header} from './header';
export {default as Login} from './login';
export {default as Register} from './register';
export {default as PublicRoutines} from './public-routines'
export {default as Footer} from './footer'
export {default as CreateRoutine} from './create-routine'
export {default as ThankYouForRegistering} from './thank-you-for-registering'
export {default as MyRoutines} from './my-routines'
export {default as Activities} from './activities'